### ISSUE TITLE
Is this crate still maintained?

### ISSUE THREAD

**Issue by Maher4Ever** [hashmismatch/fsm.rs#4]
Hello @rudib,

Thank you for making the only Rust crate that helps in implementing hierarchical state machines. However, the last version has tests commented-out and hasn't been updated in quite a while.

Has there been any development behind the scenes on this crate? Or is it an abandoned project at this point? If the latter is true, do you have any suggestions for alternatives?

**Comment by rudib** [comment]
Nope, no development. The project was/is very ambitious and I don't have a use case for it right now, so it's sitting here. 

The main improvement that I'd love to see is a function-based API instead of the current one with the complicated generic types, but that will require a very powerful AST parser.

Not sure if there are any alternatives with the exact same feature set (static transition checks with dynamic execution).

**Comment by Maher4Ever** [comment]
Ok thank you for your clarification. Follow-up question: would you still recommend using this library for new projects in 2020?

**Comment by rudib** [comment]
Well, it's released on Crates as an immutable version, so if it works for you, then why not? 👍 

I might look into re-engineering this from the ground up with a new API, unless I find some community project that provides the features that I'm looking for in a state machine library.

**Comment by rudib** [comment]
BTW, I have found some old work on my local repos with the new function API, I've pushed it into a branch. Luckily it actually compiles and the tests pass, so it might be useful to someone! Now that I have some time over the new year's break, I might look into this again and push it out as a rework of this lib from the ground up, with fewer features than the current `master` branch, but at least to have a working core. I'm working on a personal project that would benefit from this again, that's all :)

https://github.com/hashmismatch/fsm.rs/blob/fn_api_old_prototype/fsm_tests/tests/fsm_fn.rs
